// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaBanco.WebApi.Data;

#nullable disable

namespace PruebaBanco.WebApi.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    partial class BancoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaBanco.WebApi.Models.Movimiento.TransaccionesEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTarjeta")
                        .HasColumnType("int");

                    b.Property<double?>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("TipoTransaccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("IdTarjeta");

                    b.ToTable("TransaccionesTarjeta");
                });

            modelBuilder.Entity("PruebaBanco.WebApi.Models.Tarjetas.TarjetasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("MontoOtorgado")
                        .HasColumnType("float");

                    b.Property<string>("NombreTitular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTarjeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PorcentajeInteres")
                        .HasColumnType("float");

                    b.Property<double?>("PorcentajeInteresMinimo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("PruebaBanco.WebApi.Models.Movimiento.TransaccionesEntity", b =>
                {
                    b.HasOne("PruebaBanco.WebApi.Models.Tarjetas.TarjetasEntity", "TarjetaNavegation")
                        .WithMany("MovimientosTarjeta")
                        .HasForeignKey("IdTarjeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarjetaNavegation");
                });

            modelBuilder.Entity("PruebaBanco.WebApi.Models.Tarjetas.TarjetasEntity", b =>
                {
                    b.Navigation("MovimientosTarjeta");
                });
#pragma warning restore 612, 618
        }
    }
}
